basePath: /
definitions:
  entity.Card:
    properties:
      answer:
        type: string
      created_at:
        type: string
      deck_id:
        type: string
      id:
        type: string
      last_review:
        type: string
      next_review:
        type: string
      num_reviews:
        type: integer
      question:
        type: string
      sm2_ef:
        type: number
      sm2_i:
        type: integer
      sm2_n:
        type: integer
      user_id:
        type: string
      wrong_answers:
        items:
          type: string
        type: array
    type: object
  entity.DeckWithReviewCards:
    properties:
      cards:
        items:
          $ref: '#/definitions/entity.Card'
        type: array
      created_at:
        type: string
      id:
        type: string
      is_global:
        type: boolean
      name:
        type: string
      user_id:
        type: string
    type: object
  handler.CreateCardRequest:
    properties:
      answer:
        type: string
      deck_id:
        type: string
      question:
        type: string
      wrong_answers:
        items:
          type: string
        type: array
    required:
    - answer
    - deck_id
    - question
    - wrong_answers
    type: object
  handler.CreateCardResponse:
    properties:
      success:
        type: boolean
    type: object
  handler.CreateDeckRequest:
    properties:
      name:
        type: string
    required:
    - name
    type: object
  handler.CreateDeckResponse:
    properties:
      success:
        type: boolean
    type: object
  handler.ErrorResponse:
    properties:
      error:
        type: string
    type: object
  handler.LoginResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handler.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  handler.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
  handler.SignupResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
    type: object
info:
  contact:
    email: hynduf@gmail.com
    name: API Support
  description: Backend server for VietCard application
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: VietCard Backend API
  version: "1.0"
paths:
  /api/card/create:
    post:
      consumes:
      - application/json
      description: Create New Card
      parameters:
      - description: Create Card Request
        in: body
        name: create_card_request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateCardRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CreateCardResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create New Card
      tags:
      - card
  /api/deck/create:
    post:
      consumes:
      - application/json
      description: Create New Deck
      parameters:
      - description: Create Deck Request
        in: body
        name: create_deck_request
        required: true
        schema:
          $ref: '#/definitions/handler.CreateDeckRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.CreateDeckResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Create New Deck
      tags:
      - deck
  /api/deck/review-cards:
    get:
      description: Get Deck With Review Cards Of Logged In User
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/entity.DeckWithReviewCards'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      security:
      - ApiKeyAuth: []
      summary: Get Deck With Review Cards Of Logged In User
      tags:
      - deck
  /api/login:
    post:
      consumes:
      - multipart/form-data
      description: Log In
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.LoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Log In
      tags:
      - user
  /api/refresh:
    post:
      consumes:
      - application/json
      description: Refresh Token
      parameters:
      - description: Refresh Token Request
        in: body
        name: refresh_token_request
        required: true
        schema:
          $ref: '#/definitions/handler.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.RefreshTokenResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Refresh Token
      tags:
      - user
  /api/signup:
    post:
      consumes:
      - multipart/form-data
      description: Sign Up
      parameters:
      - in: formData
        name: email
        required: true
        type: string
      - in: formData
        name: name
        required: true
        type: string
      - in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.SignupResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Sign Up
      tags:
      - user
securityDefinitions:
  ApiKeyAuth:
    description: Description for what is this security definition being used
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
